### ISSUE TITLE
Add support for Kubernetes

### ISSUE THREAD

**Issue by lukasvecerka23** [bitswan-space/bitswan-gitops-cli#47]

**Comment by lukasvecerka23** [comment]
# Proposed architecture

### Automation Server

- namespace
- automation server daemon - Deployment + Service
- some other services - Deployment + Service

### Workspace

- child namespace of automation server https://kubernetes.io/blog/2020/08/14/introducing-hierarchical-namespaces/
- code server - Deployment + Service
- gitops (deprecated?)
- other services - Kafka, CouchDB, …
- ingress (on workspace level or on automation server level?)
- secrets

### Automation

- Deployment + Service under workspace namespace

## CLI / Deployment Flow

### Automation Server Registration

- CLI creates Kubernetes manifest with
    - automation server namespace
    - Deployment + Service for daemon
    - ingress?
- apply it with Kubernetes API or kubectl

```yaml
# Generated example by GPT
# Namespace pro Automation Server
apiVersion: v1
kind: Namespace
metadata:
  name: automation-server-123
---
# Deployment Automation Server Daemon
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-server-daemon
  namespace: automation-server-123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation-server-daemon
  template:
    metadata:
      labels:
        app: automation-server-daemon
    spec:
      containers:
      - name: daemon
        image: your-registry/automation-server-daemon:latest
        ports:
        - containerPort: 8080
---
# Service pro Automation Server Daemon
apiVersion: v1
kind: Service
metadata:
  name: automation-server-daemon-svc
  namespace: automation-server-123
spec:
  selector:
    app: automation-server-daemon
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
```

### Workspace creation

- CLI creates manifest with
    - workspace namespace
    - Deployments + Services for code-server, gitops?? and other services
    - Secrets
    - ingress?
- add ingress record for code server
- apply it using Kubernetes API or kubectl

```yaml
# Namespace pro workspace
apiVersion: v1
kind: Namespace
metadata:
  name: workspace-abc
---
# Deployment code-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: workspace-abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: your-registry/code-server:latest
        ports:
        - containerPort: 8080
---
# Service code-server
apiVersion: v1
kind: Service
metadata:
  name: code-server-svc
  namespace: workspace-abc
spec:
  selector:
    app: code-server
  ports:
  - port: 80
    targetPort: 8080
---
# Deployment GitOps agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-agent
  namespace: workspace-abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-agent
  template:
    metadata:
      labels:
        app: gitops-agent
    spec:
      containers:
      - name: gitops-agent
        image: your-registry/gitops-agent:latest
---
# Service GitOps
apiVersion: v1
kind: Service
metadata:
  name: gitops-agent-svc
  namespace: workspace-abc
spec:
  selector:
    app: gitops-agent
  ports:
  - port: 80
    targetPort: 8080
---
# Ingress for code-server
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workspace-abc-ingress
  namespace: workspace-abc
spec:
  rules:
  - host: workspace-abc.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server-svc
            port:
              number: 80

```

### Automation deployment

- AC daemon or gitops creates manifest with
    - Deployment + Service of workspace under workspace namespace
- apply Secrets from workspace
- add record to Ingress if automation is exposed

```yaml
# Automation deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-xyz
  namespace: workspace-abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation-xyz
  template:
    metadata:
      labels:
        app: automation-xyz
    spec:
      containers:
      - name: automation-xyz
        image: your-registry/automation-xyz:latest
        envFrom:
        - secretRef:
            name: workspace-abc-secrets
---
# Service for automation
apiVersion: v1
kind: Service
metadata:
  name: automation-xyz-svc
  namespace: workspace-abc
spec:
  selector:
    app: pipeline-xyz
  ports:
  - port: 8080
    targetPort: 8080
---
# Ingress (if automation is exposed)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workspace-abc-ingress
  namespace: workspace-abc
spec:
  rules:
  - host: automation-abc.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: automation-xyz-svc
            port:
              number: 8080
```

## Changes

### Automation Server CLI

- generate manifest for daemon
- generation of manifest and ingress for new workspace
- communication with kubernetes control (via API or via kubectl)

### GitOps

- generation of manifest for new automation
- ingress setup for exposed automations
- communication with kubernetes control
- custom PRE images needs to be stored in some private container registry
- the gitops functionality may be moved to AC daemon

## Custom PREs
- they needs to be stored in some private container registry

@timthelion what do you think?
